/**
 * Stubs for the GenOffice slides preload surface.
 *
 * `SlidesApi` is 180 members and the renderer calls a scattered handful of them
 * during bootstrap — the first run died on `clipboardProbe`, which is not a
 * method anyone would guess from the outside. Rather than discover them one
 * crash at a time, every member the interface declares gets a stub that returns
 * the right SHAPE (array, null, boolean, unsubscribe), and the shim overrides
 * the ones that are actually implemented.
 *
 * A stub that returns the wrong shape is worse than a missing method: the
 * renderer would receive `undefined` where it expects a list and fail somewhere
 * further from the cause.
 *
 * Generated from apps/slides/src/shared/ipc.ts. Regenerate with
 * scripts/gen-api-stubs.mjs; it is checked in because it is read, not written.
 */
export const slidesApiStubs: Record<string, unknown> = {
  getLanguage: () => Promise.resolve(null),
  onLanguageChanged: () => () => undefined,
  getTheme: () => Promise.resolve(null),
  onThemeChanged: () => () => undefined,
  getAutoSaveDefault: () => Promise.resolve(null),
  onAutoSaveDefaultChanged: () => () => undefined,
  getAiPanelPrefs: () => Promise.resolve(null),
  onAiPanelPrefsChanged: () => () => undefined,
  onChromePressed: () => () => undefined,
  setShowFullScreen: () => Promise.resolve(),
  openPptx: () => Promise.resolve(null),
  openPptxPath: () => Promise.resolve(null),
  privateFontFaces: () => Promise.resolve(false),
  privateFontData: () => Promise.resolve(null),
  fontCatalog: () => Promise.resolve(null),
  fontDownload: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  fontInstallLocal: () => Promise.resolve([]),
  fontMissing: () => Promise.resolve([]),
  onFontsChanged: () => () => undefined,
  consumePendingOpen: () => Promise.resolve(null),
  consumeHeadlessExport: () => Promise.resolve(null),
  headlessExportDone: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  newBlank: () => Promise.resolve(null),
  landGeneratedPages: () => Promise.resolve([]),
  cloudGenStatus: () => Promise.resolve(false),
  cloudGeneratePage: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  localGeneratePage: () => Promise.resolve([]),
  editText: () => Promise.resolve(null),
  setElementFont: () => Promise.resolve(null),
  setElementParagraphFormat: () => Promise.resolve(null),
  findReplace: () => Promise.resolve([]),
  setSlideLayout: () => Promise.resolve(null),
  setSlideSize: () => Promise.resolve([]),
  getSlideSize: () => Promise.resolve(null),
  editTransform: () => Promise.resolve(null),
  editConnectorEndpoints: () => Promise.resolve(null),
  batchEditTransform: () => Promise.resolve(null),
  getRenderSlides: () => Promise.resolve([]),
  editPictureSrcRect: () => Promise.resolve(null),
  editPictureOpacity: () => Promise.resolve(null),
  editImageFill: () => Promise.resolve(null),
  changeShape: () => Promise.resolve(null),
  setShapeAdjust: () => Promise.resolve(null),
  setTextAnchor: () => Promise.resolve(null),
  setEffects: () => Promise.resolve(null),
  setTextBodyProps: () => Promise.resolve(null),
  clipboardExternal: () => Promise.resolve(null),
  groupElements: () => Promise.resolve(null),
  ungroupElement: () => Promise.resolve(null),
  addElement: () => Promise.resolve(null),
  deleteElement: () => Promise.resolve(null),
  addSlide: () => Promise.resolve([]),
  addBlankSlide: () => Promise.resolve([]),
  copySlide: () => Promise.resolve(false),
  pasteSlide: () => Promise.resolve([]),
  repasteSlide: () => Promise.resolve([]),
  hasSlideClipboard: () => Promise.resolve(false),
  clipboardProbe: () => Promise.resolve(false),
  deleteSlide: () => Promise.resolve([]),
  reorderElement: () => Promise.resolve(null),
  editTableCell: () => Promise.resolve(null),
  tableStructure: () => Promise.resolve(null),
  tableMerge: () => Promise.resolve(null),
  setTableColWidth: () => Promise.resolve(null),
  setTableRowHeight: () => Promise.resolve(null),
  setTableCellAnchor: () => Promise.resolve(null),
  editFill: () => Promise.resolve(null),
  editStroke: () => Promise.resolve(null),
  flipElements: () => Promise.resolve(null),
  editBackground: () => Promise.resolve([]),
  pickPictureFile: () => Promise.resolve(null),
  insertImage: () => Promise.resolve(null),
  copyElements: () => Promise.resolve(0),
  copyElementsImage: () => Promise.resolve(false),
  pasteElements: () => Promise.resolve([]),
  duplicateElements: () => Promise.resolve([]),
  addTable: () => Promise.resolve(null),
  addInk: () => Promise.resolve(null),
  addChart: () => Promise.resolve(null),
  addSmartArt: () => Promise.resolve(null),
  addImageBytes: () => Promise.resolve(null),
  replacePictureBytes: () => Promise.resolve(null),
  insertMedia: () => Promise.resolve(null),
  addMediaBytes: () => Promise.resolve(null),
  getMediaData: () => Promise.resolve(null),
  insertModel3d: () => Promise.resolve(null),
  setLink: () => Promise.resolve(null),
  getLink: () => Promise.resolve(null),
  getSlideLinks: () => Promise.resolve(''),
  getRunLinks: () => Promise.resolve(''),
  applyHeaderFooter: () => Promise.resolve([]),
  getHeaderFooter: () => Promise.resolve(null),
  applyTheme: () => Promise.resolve([]),
  setTransition: () => Promise.resolve(false),
  getTransition: () => Promise.resolve(null),
  setAdvanceTimes: () => Promise.resolve(false),
  getAnimations: () => Promise.resolve([]),
  getShapeKeys: () => Promise.resolve([]),
  setAnimations: () => Promise.resolve(false),
  setSlideHidden: () => Promise.resolve(null),
  getSections: () => Promise.resolve([]),
  setSections: () => Promise.resolve([]),
  addSection: () => Promise.resolve([]),
  renameSection: () => Promise.resolve([]),
  removeSection: () => Promise.resolve([]),
  moveSection: () => Promise.resolve([]),
  moveSlide: () => Promise.resolve([]),
  getNotes: () => Promise.resolve(''),
  setNotes: () => Promise.resolve(false),
  getComments: () => Promise.resolve([]),
  addComment: () => Promise.resolve([]),
  deleteComment: () => Promise.resolve([]),
  nativeClipboard: () => Promise.resolve(),
  beginHistoryBatch: () => Promise.resolve(false),
  endHistoryBatch: () => Promise.resolve(null),
  applyEditScript: () => Promise.resolve(null),
  applyTxn: () => Promise.resolve(null),
  aiSnapshotRestore: () => Promise.resolve([]),
  undo: () => Promise.resolve([]),
  redo: () => Promise.resolve([]),
  editTableStyle: () => Promise.resolve(null),
  editChart: () => Promise.resolve(null),
  getChartColorSchemes: () => Promise.resolve([]),
  getChartData: () => Promise.resolve([]),
  pickExportDir: () => Promise.resolve(null),
  exportImages: () => Promise.resolve(null),
  pickExportPdfPath: () => Promise.resolve(null),
  exportPdf: () => Promise.resolve(null),
  printSlides: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  save: () => Promise.resolve([]),
  saveAs: () => Promise.resolve([]),
  onCloseSaveRequest: () => () => undefined,
  onHistoryChanged: () => () => undefined,
  onDeckChanged: () => () => undefined,
  reportCloseSaveResult: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  setAutoSavePref: () => undefined,
  isDirty: () => Promise.resolve(false),
  getRecentFiles: () => Promise.resolve([]),
  onMenuCommand: () => () => undefined,
  onOpened: () => () => undefined,
  onRenamed: () => () => undefined,
  getAiSettings: () => Promise.resolve(null),
  setAiSettings: () => Promise.resolve(),
  aiStream: () => Promise.resolve(),
  aiStreamCancel: () => Promise.resolve(),
  aiGskStatus: () => Promise.resolve(null),
  aiGskLogin: () => Promise.resolve(),
  aiLogRunFailure: () => Promise.resolve(),
  webSearch: () => Promise.resolve(''),
  imageSearch: () => Promise.resolve(''),
  insertImageUrl: () => Promise.resolve(null),
  replacePictureUrl: () => Promise.resolve(null),
  generateImage: () => Promise.resolve(''),
  analyzeMedia: () => Promise.resolve(''),
  gskStatus: () => Promise.resolve(false),
  onAiStream: () => () => undefined,
  saveStyleSidecar: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  saveStyleTemplate: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  listStyleTemplates: () => Promise.resolve(''),
  loadStyleTemplate: () => Promise.resolve({ ok: false, error: '尚未接入宿主' }),
  addSlideWithLayout: () => Promise.resolve([]),
  getLayouts: () => Promise.resolve(null),
  masterEnter: () => Promise.resolve(null),
  masterOpen: () => Promise.resolve(null),
  masterClose: () => Promise.resolve([]),
  masterEditText: () => Promise.resolve(null),
  masterEditTransform: () => Promise.resolve(null),
  masterEditFill: () => Promise.resolve(null),
  masterEditStroke: () => Promise.resolve(null),
  masterDeleteElement: () => Promise.resolve(null),
  presenterStart: () => Promise.resolve(false),
  presenterSync: () => undefined,
  presenterInk: () => undefined,
  presenterSwap: () => Promise.resolve(false),
  presenterEnd: () => Promise.resolve(),
  audienceReady: () => Promise.resolve(null),
  audienceNav: () => undefined,
  onShowSync: () => () => undefined,
  onShowInk: () => () => undefined,
  onAudienceNav: () => () => undefined,
};
