/**
 * Stubs for GenOffice's `SlidesApi` (window.slidesApi).
 *
 * 181 members, of which the renderer calls a scattered handful during bootstrap —
 * none of them guessable from the outside (the first slides run died on
 * `clipboardProbe`). Each returns the SHAPE its declaration promises, so a
 * stubbed call degrades to "feature unavailable" rather than blowing up
 * somewhere far from the cause.
 *
 * Every real implementation lives in the shim next to this file, spread over
 * the top of this object.
 *
 * Generated from apps/slides/src/shared/ipc.ts by scripts/gen-api-stubs.mjs. Regenerate rather
 * than edit — but do check it in: it is read far more often than written.
 */
export const slidesApiStubs: Record<string, unknown> = {
  getLanguage: () => Promise.resolve(null),
  onLanguageChanged: () => undefined,
  getTheme: () => Promise.resolve(null),
  onThemeChanged: () => () => undefined,
  getAutoSaveDefault: () => Promise.resolve(null),
  onAutoSaveDefaultChanged: () => () => undefined,
  getAiPanelPrefs: () => Promise.resolve(null),
  setAiPanelPrefs: () => Promise.resolve(null),
  onAiPanelPrefsChanged: () => () => undefined,
  onChromePressed: () => () => undefined,
  setShowFullScreen: () => Promise.resolve(),
  openPptx: () => Promise.resolve(null),
  openPptxPath: () => Promise.resolve(null),
  privateFontFaces: () => Promise.resolve(false),
  privateFontData: () => Promise.resolve(null),
  fontCatalog: () => Promise.resolve(null),
  fontDownload: () => Promise.resolve(false),
  fontInstallLocal: () => Promise.resolve([]),
  fontMissing: () => Promise.resolve([]),
  onFontsChanged: () => () => undefined,
  consumePendingOpen: () => Promise.resolve(null),
  consumeHeadlessExport: () => Promise.resolve(null),
  headlessExportDone: () => undefined,
  newBlank: () => Promise.resolve(null),
  landGeneratedPages: () => undefined,
  cloudGenStatus: () => Promise.resolve(false),
  cloudGeneratePage: () => undefined,
  localGeneratePage: () => undefined,
  editText: () => Promise.resolve(null),
  setElementFont: () => Promise.resolve(null),
  setElementParagraphFormat: () => Promise.resolve(null),
  findReplace: () => undefined,
  setSlideLayout: () => Promise.resolve(null),
  setSlideSize: () => Promise.resolve([]),
  getSlideSize: () => Promise.resolve(null),
  editTransform: () => Promise.resolve(null),
  editConnectorEndpoints: () => Promise.resolve(null),
  batchEditTransform: () => Promise.resolve(null),
  getRenderSlides: () => Promise.resolve([]),
  editPictureSrcRect: () => Promise.resolve(null),
  editPictureOpacity: () => Promise.resolve(null),
  editImageFill: () => Promise.resolve(null),
  changeShape: () => undefined,
  setShapeAdjust: () => undefined,
  setTextAnchor: () => undefined,
  setEffects: () => undefined,
  setTextBodyProps: () => undefined,
  clipboardExternal: () => Promise.resolve(null),
  groupElements: () => Promise.resolve(null),
  ungroupElement: () => Promise.resolve(null),
  addElement: () => Promise.resolve(null),
  deleteElement: () => Promise.resolve(null),
  addSlide: () => Promise.resolve([]),
  addBlankSlide: () => Promise.resolve([]),
  copySlide: () => Promise.resolve(false),
  pasteSlide: () => undefined,
  repasteSlide: () => undefined,
  hasSlideClipboard: () => Promise.resolve(false),
  clipboardProbe: () => Promise.resolve(false),
  deleteSlide: () => Promise.resolve([]),
  reorderElement: () => Promise.resolve(null),
  editTableCell: () => Promise.resolve(null),
  tableStructure: () => undefined,
  tableMerge: () => Promise.resolve(null),
  setTableColWidth: () => Promise.resolve(null),
  setTableRowHeight: () => Promise.resolve(null),
  setTableCellAnchor: () => Promise.resolve(null),
  editFill: () => Promise.resolve(null),
  editStroke: () => Promise.resolve(null),
  flipElements: () => Promise.resolve(null),
  editBackground: () => Promise.resolve([]),
  pickPictureFile: () => Promise.resolve(null),
  insertImage: () => undefined,
  copyElements: () => Promise.resolve(0),
  copyElementsImage: () => Promise.resolve(false),
  pasteElements: () => undefined,
  duplicateElements: () => undefined,
  addTable: () => Promise.resolve(null),
  addInk: () => Promise.resolve(null),
  addChart: () => Promise.resolve(null),
  addSmartArt: () => Promise.resolve(null),
  addImageBytes: () => undefined,
  replacePictureBytes: () => undefined,
  insertMedia: () => undefined,
  addMediaBytes: () => Promise.resolve(null),
  getMediaData: () => undefined,
  insertModel3d: () => undefined,
  setLink: () => Promise.resolve(null),
  getLink: () => Promise.resolve(null),
  getSlideLinks: () => Promise.resolve(''),
  getRunLinks: () => undefined,
  applyHeaderFooter: () => Promise.resolve([]),
  getHeaderFooter: () => undefined,
  applyTheme: () => Promise.resolve([]),
  setTransition: () => Promise.resolve(false),
  getTransition: () => Promise.resolve(null),
  setAdvanceTimes: () => Promise.resolve(false),
  getAnimations: () => Promise.resolve([]),
  getShapeKeys: () => Promise.resolve([]),
  setAnimations: () => Promise.resolve(false),
  setSlideHidden: () => Promise.resolve(null),
  getSections: () => Promise.resolve([]),
  setSections: () => Promise.resolve([]),
  addSection: () => Promise.resolve([]),
  renameSection: () => Promise.resolve([]),
  removeSection: () => Promise.resolve([]),
  moveSection: () => undefined,
  moveSlide: () => Promise.resolve([]),
  getNotes: () => Promise.resolve(''),
  setNotes: () => Promise.resolve(false),
  getComments: () => Promise.resolve([]),
  addComment: () => Promise.resolve([]),
  deleteComment: () => Promise.resolve([]),
  nativeClipboard: () => Promise.resolve(),
  beginHistoryBatch: () => Promise.resolve(false),
  endHistoryBatch: () => Promise.resolve(null),
  applyEditScript: () => undefined,
  applyTxn: () => Promise.resolve(null),
  aiSnapshotRestore: () => Promise.resolve([]),
  undo: () => Promise.resolve([]),
  redo: () => Promise.resolve([]),
  editTableStyle: () => undefined,
  editChart: () => Promise.resolve(null),
  getChartColorSchemes: () => Promise.resolve([]),
  getChartData: () => undefined,
  pickExportDir: () => Promise.resolve(null),
  exportImages: () => Promise.resolve(null),
  pickExportPdfPath: () => Promise.resolve(null),
  exportPdf: () => Promise.resolve(null),
  printSlides: () => Promise.resolve(false),
  save: () => Promise.resolve([]),
  saveAs: () => undefined,
  onCloseSaveRequest: () => () => undefined,
  onHistoryChanged: () => () => undefined,
  onDeckChanged: () => undefined,
  reportCloseSaveResult: () => undefined,
  setAutoSavePref: () => undefined,
  isDirty: () => Promise.resolve(false),
  getRecentFiles: () => Promise.resolve([]),
  onMenuCommand: () => () => undefined,
  onOpened: () => () => undefined,
  onRenamed: () => () => undefined,
  getAiSettings: () => Promise.resolve(null),
  setAiSettings: () => Promise.resolve(),
  aiStream: () => Promise.resolve(),
  aiStreamCancel: () => Promise.resolve(),
  aiGskStatus: () => Promise.resolve(null),
  aiGskLogin: () => Promise.resolve(),
  aiLogRunFailure: () => Promise.resolve(),
  webSearch: () => undefined,
  imageSearch: () => undefined,
  insertImageUrl: () => undefined,
  replacePictureUrl: () => undefined,
  generateImage: () => undefined,
  analyzeMedia: () => undefined,
  gskStatus: () => Promise.resolve(false),
  onAiStream: () => () => undefined,
  saveStyleSidecar: () => undefined,
  saveStyleTemplate: () => undefined,
  listStyleTemplates: () => Promise.resolve(''),
  loadStyleTemplate: () => undefined,
  addSlideWithLayout: () => undefined,
  getLayouts: () => Promise.resolve(null),
  masterEnter: () => Promise.resolve(null),
  masterOpen: () => Promise.resolve(null),
  masterClose: () => Promise.resolve([]),
  masterEditText: () => Promise.resolve(null),
  masterEditTransform: () => Promise.resolve(null),
  masterEditFill: () => Promise.resolve(null),
  masterEditStroke: () => Promise.resolve(null),
  masterDeleteElement: () => Promise.resolve(null),
  presenterStart: () => Promise.resolve(false),
  presenterSync: () => undefined,
  presenterInk: () => undefined,
  presenterSwap: () => Promise.resolve(false),
  presenterEnd: () => Promise.resolve(),
  audienceReady: () => Promise.resolve(null),
  audienceNav: () => undefined,
  onShowSync: () => () => undefined,
  onShowInk: () => () => undefined,
  onAudienceNav: () => () => undefined,
};
