import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';
import { usePanelStore, type PanelEntry, type PanelRegion } from '@/stores/panel-store';
import { useUIStore } from '@/stores/ui-store';
import { panelIcon } from './panel-icons';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

/**
 * Rail icon. Plugin-provided icons render as a CSS-mask stencil — the SVG's
 * alpha channel colors with `currentColor`, so plugin icons match the host's
 * lucide glyphs across themes and hover/active states (masks never execute
 * scripts either). Falls back to the vocabulary icon when the asset fails.
 */
function RailIcon({ panel }: { panel: PanelEntry }) {
  const [broken, setBroken] = useState(false);
  const Icon = panelIcon(panel.icon);

  useEffect(() => {
    setBroken(false);
    if (!panel.iconUrl) return;
    // Probe the asset — CSS masks fail silently, so detect via Image().
    const probe = new Image();
    probe.onerror = () => setBroken(true);
    probe.src = panel.iconUrl;
    return () => { probe.onerror = null; };
  }, [panel.iconUrl]);

  if (panel.iconUrl && !broken) {
    return (
      <span
        aria-hidden
        className="bg-current"
        // Inline size — fractional Tailwind utilities (h-4.5) may not be
        // generated by JIT; 24px matches the effective size of the lucide
        // glyphs beside it.
        style={{
          width: 24,
          height: 24,
          WebkitMaskImage: `url(${panel.iconUrl})`,
          maskImage: `url(${panel.iconUrl})`,
          WebkitMaskSize: 'contain',
          maskSize: 'contain',
          WebkitMaskRepeat: 'no-repeat',
          maskRepeat: 'no-repeat',
          WebkitMaskPosition: 'center',
          maskPosition: 'center',
        }}
      />
    );
  }
  return <Icon className="h-6 w-6" />;
}

function RailButton({ panel, region }: { panel: PanelEntry; region: PanelRegion }) {
  const activePanelId = usePanelStore((s) => s.activePanelIds[region]);
  const openPanel = usePanelStore((s) => s.openPanel);
  const setRightPanelOpen = useUIStore((s) => s.setRightPanelOpen);
  const runtime = usePanelStore((s) => s.runtime[panel.id]);

  const active = activePanelId === panel.id;
  const badge = runtime?.badge;
  const pending = runtime?.pending;
  // The rail sits beside its content column, so the indicator goes on the
  // inner edge: right edge for a left rail, left edge for a right rail.
  const isLeft = region === 'left';

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          aria-label={panel.title}
          aria-pressed={active}
          data-panel-id={panel.id}
          data-state={active ? 'active' : 'inactive'}
          data-pending={pending ? 'true' : undefined}
          onClick={() => {
            openPanel(panel.id, { focus: true });
            // A rail click on the right is an explicit open — surface that side.
            // The left column is toggled from the title bar and is already
            // visible whenever its rail is reachable.
            if (region === 'right') setRightPanelOpen(true);
          }}
          className={cn(
            'relative flex h-10 w-10 items-center justify-center rounded-md text-muted-foreground transition-colors',
            'hover:bg-accent hover:text-accent-foreground',
            active && 'bg-accent text-accent-foreground',
            pending && !active && 'text-foreground',
          )}
        >
          <RailIcon panel={panel} />
          {badge !== undefined && badge !== null && badge !== '' && (
            <span
              data-panel-badge
              className={cn(
                'absolute -top-0.5 min-w-[16px] rounded-full bg-primary px-1 text-[10px] font-medium leading-4 text-primary-foreground',
                isLeft ? '-left-0.5' : '-right-0.5',
              )}
            >
              {badge}
            </span>
          )}
          {pending && badge === undefined && (
            <span className={cn('absolute top-1 h-2 w-2 animate-pulse rounded-full bg-primary', isLeft ? 'left-1' : 'right-1')} />
          )}
          {active && (
            <span
              className={cn(
                'absolute top-1/2 h-5 w-0.5 -translate-y-1/2 bg-primary',
                isLeft ? 'right-0 rounded-l' : 'left-0 rounded-r',
              )}
            />
          )}
        </button>
      </TooltipTrigger>
      <TooltipContent side={isLeft ? 'right' : 'left'}>{panel.title}</TooltipContent>
    </Tooltip>
  );
}

/**
 * Icon rail for one sidebar column: the panel switcher. Host panels and plugin
 * panels live side by side; badges/active dots stay visible even when the panel
 * body is collapsed. The plugin center is a regular rail entry (host:plugins) —
 * no separate bottom "+" launcher.
 *
 * Panels are split into two groups by `anchor`; the bottom group is pushed to
 * the far end, which is where configuration-style panels belong.
 */
export function PanelRail({ region = 'right' }: { region?: PanelRegion }) {
  const panels = usePanelStore((s) => s.panels);
  // Hidden panels are openable via panel.open / events but get no rail button.
  const railPanels = panels
    .filter((p) => p.region === region && !p.hidden)
    .sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

  const topGroup = railPanels.filter((p) => p.anchor !== 'bottom');
  const bottomGroup = railPanels.filter((p) => p.anchor === 'bottom');

  return (
    <div
      className="flex h-full w-12 shrink-0 flex-col items-center gap-1 border-r bg-background py-2"
      data-testid={`panel-rail-${region}`}
      data-panel-rail-region={region}
    >
      {topGroup.map((panel) => (
        <RailButton key={panel.id} panel={panel} region={region} />
      ))}
      {bottomGroup.length > 0 && (
        <>
          <div className="flex-1" />
          {bottomGroup.map((panel) => (
            <RailButton key={panel.id} panel={panel} region={region} />
          ))}
        </>
      )}
    </div>
  );
}
