import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';
import { usePanelStore, type PanelEntry } from '@/stores/panel-store';
import { panelIcon } from './panel-icons';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';

/**
 * Rail icon. Plugin-provided icons render as a CSS-mask stencil — the SVG's
 * alpha channel colors with `currentColor`, so plugin icons match the host's
 * lucide glyphs across themes and hover/active states (masks never execute
 * scripts either). Falls back to the vocabulary icon when the asset fails.
 */
function RailIcon({ panel }: { panel: PanelEntry }) {
  const [broken, setBroken] = useState(false);
  const Icon = panelIcon(panel.icon);

  useEffect(() => {
    setBroken(false);
    if (!panel.iconUrl) return;
    // Probe the asset — CSS masks fail silently, so detect via Image().
    const probe = new Image();
    probe.onerror = () => setBroken(true);
    probe.src = panel.iconUrl;
    return () => { probe.onerror = null; };
  }, [panel.iconUrl]);

  if (panel.iconUrl && !broken) {
    return (
      <span
        aria-hidden
        className="bg-current"
        // Inline size — fractional Tailwind utilities (h-4.5) may not be
        // generated by JIT; 24px matches the effective size of the lucide
        // glyphs beside it.
        style={{
          width: 24,
          height: 24,
          WebkitMaskImage: `url(${panel.iconUrl})`,
          maskImage: `url(${panel.iconUrl})`,
          WebkitMaskSize: 'contain',
          maskSize: 'contain',
          WebkitMaskRepeat: 'no-repeat',
          maskRepeat: 'no-repeat',
          WebkitMaskPosition: 'center',
          maskPosition: 'center',
        }}
      />
    );
  }
  return <Icon className="h-4.5 w-4.5" />;
}

function RailButton({ panel }: { panel: PanelEntry }) {
  const activePanelId = usePanelStore((s) => s.activePanelId);
  const openPanel = usePanelStore((s) => s.openPanel);
  const runtime = usePanelStore((s) => s.runtime[panel.id]);

  const active = activePanelId === panel.id;
  const badge = runtime?.badge;
  const pending = runtime?.pending;

  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          aria-label={panel.title}
          aria-pressed={active}
          data-panel-id={panel.id}
          data-state={active ? 'active' : 'inactive'}
          data-pending={pending ? 'true' : undefined}
          onClick={() => openPanel(panel.id, { focus: true })}
          className={cn(
            'relative flex h-10 w-10 items-center justify-center rounded-md text-muted-foreground transition-colors',
            'hover:bg-accent hover:text-accent-foreground',
            active && 'bg-accent text-accent-foreground',
            pending && !active && 'text-foreground',
          )}
        >
          <RailIcon panel={panel} />
          {badge !== undefined && badge !== null && badge !== '' && (
            <span
              data-panel-badge
              className="absolute -right-0.5 -top-0.5 min-w-[16px] rounded-full bg-primary px-1 text-[10px] font-medium leading-4 text-primary-foreground"
            >
              {badge}
            </span>
          )}
          {pending && badge === undefined && (
            <span className="absolute right-1 top-1 h-2 w-2 animate-pulse rounded-full bg-primary" />
          )}
          {active && <span className="absolute left-0 top-1/2 h-5 w-0.5 -translate-y-1/2 rounded-r bg-primary" />}
        </button>
      </TooltipTrigger>
      <TooltipContent side="left">{panel.title}</TooltipContent>
    </Tooltip>
  );
}

/**
 * Right-edge icon rail: the plugin panel switcher. Host panels and plugin
 * panels live side by side; badges/active dots stay visible even when the
 * panel body is collapsed. The plugin center is a regular rail entry
 * (host:plugins, first) — no separate bottom "+" launcher.
 */
export function PanelRail() {
  const panels = usePanelStore((s) => s.panels);
  // Auxiliary panels (hidden / companion) are not listed — one plugin, one
  // rail button. Companions render inside their primary panel's body.
  const railPanels = panels.filter((p) => !p.hidden && !p.companionOf);

  return (
    <div className="flex h-full w-12 shrink-0 flex-col items-center gap-1 border-r bg-background py-2" data-testid="panel-rail">
      {railPanels.map((panel) => (
        <RailButton key={panel.id} panel={panel} />
      ))}
    </div>
  );
}
