/**
 * Recording script — injected into the webview page via page.evaluate().
 *
 * Captures user interactions (click, input, change, scroll, navigation)
 * and sends them back to the main process via console.log with a special
 * prefix. The main process listens on page.on('console') to collect steps.
 *
 * Each event is converted to a structured step with a Playwright selector.
 */

/** The JS code string to inject. Uses a IIFE to avoid polluting global scope. */
export const RECORDING_SCRIPT = `
(function() {
  if (window.__piBrowserRecording) return; // Already recording
  window.__piBrowserRecording = true;
  window.__piBrowserSteps = [];

  // ── Selector generation (mirrors selector-generator.ts) ──
  function looksAutoGenerated(id) {
    if (/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(id)) return true;
    if (/^\\d+$/.test(id)) return true;
    if (/^(r\\d|vue-|__|react-|aria-)/i.test(id)) return true;
    return false;
  }

  function isInteractive(tag) {
    return ['a', 'button', 'input', 'select', 'textarea', 'label', 'summary'].includes(tag);
  }

  function generateSelector(element) {
    // 1. data-testid
    var testId = element.getAttribute('data-testid');
    if (testId) return '[data-testid="' + testId + '"]';

    // 2. id
    var id = element.getAttribute('id');
    if (id && !looksAutoGenerated(id)) {
      // CSS.escape may not exist in all contexts
      try { return '#' + CSS.escape(id); } catch(e) { return '#' + id; }
    }

    // 3. aria-label
    var ariaLabel = element.getAttribute('aria-label');
    if (ariaLabel) {
      try { return '[aria-label="' + CSS.escape(ariaLabel) + '"]'; }
      catch(e) { return '[aria-label="' + ariaLabel + '"]'; }
    }

    // 4. has-text
    var tag = element.tagName.toLowerCase();
    var text = (element.textContent || '').trim();
    if (text && text.length <= 50 && isInteractive(tag)) {
      var escapedText = text.replace(/"/g, '\\\\"');
      return tag + ':has-text("' + escapedText + '")';
    }

    // 5. role-based
    var role = element.getAttribute('role');
    if (role) {
      var name_1 = ariaLabel || text;
      if (name_1 && name_1.length <= 50) {
        var escapedName = name_1.replace(/"/g, '\\\\"');
        return 'role=' + role + '[name="' + escapedName + '"]';
      }
      return 'role=' + role;
    }

    // 6. name attribute
    var nameAttr = element.getAttribute('name');
    if (nameAttr) {
      try { return tag + '[name="' + CSS.escape(nameAttr) + '"]'; }
      catch(e) { return tag + '[name="' + nameAttr + '"]'; }
    }

    // 7. nth-child chain
    var parts = [];
    var current = element;
    while (current && current !== document.body) {
      var ct = current.tagName.toLowerCase();
      var parent = current.parentElement;
      if (!parent) { parts.unshift(ct); break; }
      var siblings = Array.from(parent.children);
      var index = siblings.indexOf(current) + 1;
      parts.unshift(ct + ':nth-child(' + index + ')');
      current = parent;
    }
    return parts.join(' > ');
  }

  function sendStep(step) {
    window.__piBrowserSteps.push(step);
    // Send to main process via console.log with special prefix
    console.log('__PI_RECORDING__' + JSON.stringify(step));
  }

  // ── Click events ──
  document.addEventListener('click', function(e) {
    var target = e.target;
    if (!target || target.nodeType !== 1) return;
    var selector = generateSelector(target);
    sendStep({
      type: 'click',
      selector: selector,
      timestamp: Date.now(),
      url: location.href,
    });
  }, true);

  // ── Input/change events (for text fields, textareas, selects) ──
  var inputDebounce = null;
  function captureInput(e) {
    var target = e.target;
    if (!target || target.nodeType !== 1) return;
    var tag = target.tagName.toLowerCase();
    if (!['input', 'textarea', 'select'].includes(tag)) return;

    var selector = generateSelector(target);
    var value = target.value;

    if (inputDebounce) clearTimeout(inputDebounce);
    inputDebounce = setTimeout(function() {
      sendStep({
        type: 'fill',
        selector: selector,
        value: value,
        timestamp: Date.now(),
        url: location.href,
      });
    }, 500); // Debounce: one fill step per input burst
  }
  document.addEventListener('input', captureInput, true);
  document.addEventListener('change', captureInput, true);

  // ── Scroll events (debounced) ──
  var scrollDebounce = null;
  document.addEventListener('scroll', function() {
    if (scrollDebounce) clearTimeout(scrollDebounce);
    scrollDebounce = setTimeout(function() {
      sendStep({
        type: 'scroll',
        direction: 'down',
        amount: Math.round(window.scrollY),
        timestamp: Date.now(),
        url: location.href,
      });
    }, 1000); // Heavily debounced — scroll isn't critical for replay
  }, true);

  // ── Navigation detection ──
  var currentUrl = location.href;
  // Poll for URL changes (single-page apps may change URL without navigation event)
  setInterval(function() {
    if (location.href !== currentUrl) {
      currentUrl = location.href;
      sendStep({
        type: 'navigate',
        url: currentUrl,
        timestamp: Date.now(),
        url: currentUrl,
      });
    }
  }, 500);

  console.log('__PI_RECORDING_STARTED__');
})();
`;

/** Prefix used to identify recording messages in console output. */
export const RECORDING_MESSAGE_PREFIX = '__PI_RECORDING__';
export const RECORDING_STARTED_MESSAGE = '__PI_RECORDING_STARTED__';
