/**
 * Selector generator — produces Playwright-compatible CSS selectors for
 * recorded elements. Priority order matches Playwright best practices.
 *
 * Priority:
 *   1. [data-testid]
 *   2. #id (if unique on the page)
 *   3. [aria-label]
 *   4. :has-text() (for buttons/links with visible text)
 *   5. role= (ARIA roles)
 *   6. nth-child chain (fallback)
 */

/** Generate a robust Playwright selector for a DOM element. */
export function generateSelector(element: Element): string {
  // 1. data-testid
  const testId = element.getAttribute('data-testid');
  if (testId) return `[data-testid="${testId}"]`;

  // 2. id (only if it looks unique — not auto-generated)
  const id = element.getAttribute('id');
  if (id && !looksAutoGenerated(id)) {
    return `#${CSS.escape(id)}`;
  }

  // 3. aria-label
  const ariaLabel = element.getAttribute('aria-label');
  if (ariaLabel) {
    return `[aria-label="${CSS.escape(ariaLabel)}"]`;
  }

  // 4. :has-text() for elements with visible text content
  const tag = element.tagName.toLowerCase();
  const text = (element.textContent ?? '').trim();
  if (text && text.length <= 50 && isInteractive(tag)) {
    // Escape quotes in text
    const escapedText = text.replace(/"/g, '\\"');
    // Use a specific tag + has-text for precision
    return `${tag}:has-text("${escapedText}")`;
  }

  // 5. role-based
  const role = element.getAttribute('role');
  if (role) {
    const name = ariaLabel ?? text;
    if (name && name.length <= 50) {
      const escapedName = name.replace(/"/g, '\\"');
      return `role=${role}[name="${escapedName}"]`;
    }
    return `role=${role}`;
  }

  // 6. name attribute (useful for form inputs)
  const name = element.getAttribute('name');
  if (name) {
    return `${tag}[name="${CSS.escape(name)}"]`;
  }

  // 7. nth-child chain fallback
  return buildNthChildSelector(element);
}

/** Check if an ID looks auto-generated (UUIDs, numeric, hash-like). */
function looksAutoGenerated(id: string): boolean {
  // UUIDs: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  if (/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(id)) return true;
  // Pure numeric or hash-like (react/vue generated)
  if (/^\d+$/.test(id)) return true;
  // Short hash prefixes like "r1_", "vue-", "#"
  if (/^(r\d|vue-|__|react-|aria-)/i.test(id)) return true;
  return false;
}

/** Check if a tag is typically interactive (good for :has-text selectors). */
function isInteractive(tag: string): boolean {
  return ['a', 'button', 'input', 'select', 'textarea', 'label', 'summary'].includes(tag);
}

/** Build a selector using nth-child chain. */
function buildNthChildSelector(element: Element): string {
  const parts: string[] = [];
  let current: Element | null = element;

  while (current && current !== document.body) {
    const tag = current.tagName.toLowerCase();
    const parent: HTMLElement | null = current.parentElement;
    if (!parent) {
      parts.unshift(tag);
      break;
    }
    const siblings: Element[] = Array.from(parent.children);
    const index = siblings.indexOf(current) + 1;
    parts.unshift(`${tag}:nth-child(${index})`);
    current = parent;
  }

  return parts.join(' > ');
}
